services:
  - type: web
    name: ddmusic
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://ddmusic:2942005dd@ddmusic.uhoifbp.mongodb.net/ddmusic1?retryWrites=true&w=majority&appName=ddmusic
      - key: SESSION_SECRET
        value: dd2942005dd
      - key: PORT
        value: 3500
